var EnglishTelugu_Airlines =
[
{PrimLang_word:"air canada",PrimLang_sound_url:"",PrimLang_translit:"air canada",PrimLangInfo:"",SecLang_word:"ఎయిర్ కెనడా",SecLang_sound_url:"",SecLang_translit:"ఎయిర్ కెనడా",Image:"http://www.logoeps.com/wp-content/uploads/AutoGen/0e285347a913924f81b0cdcbf0257c52.jpg"},
{PrimLang_word:"airtran",PrimLang_sound_url:"",PrimLang_translit:"airtran",PrimLangInfo:"",SecLang_word:"ఎయిర్ ట్రాన్",SecLang_sound_url:"",SecLang_translit:"ఎయిర్ ట్రాన్",Image:"http://www.jlhr.org/ama/orig/bronzeairtran.jpg"},
{PrimLang_word:"alaska airlines",PrimLang_sound_url:"",PrimLang_translit:"alaska airlines",PrimLangInfo:"",SecLang_word:"అలాస్కా ఎయిర్ లైన్స్",SecLang_sound_url:"",SecLang_translit:"అలాస్కా ఎయిర్ లైన్స్",Image:"http://www.seeklogo.com/images/A/Alaska_Airlines-logo-A81DD481D9-seeklogo.com.gif"},
{PrimLang_word:"american airlines",PrimLang_sound_url:"",PrimLang_translit:"american airlines",PrimLangInfo:"",SecLang_word:"అమెరికన్ ఎయిర్ లైన్స్",SecLang_sound_url:"",SecLang_translit:"అమెరికన్ ఎయిర్ లైన్స్",Image:"http://upload.wikimedia.org/wikipedia/en/d/d7/American_Airlines_logo.svg"},
{PrimLang_word:"continental airlines",PrimLang_sound_url:"",PrimLang_translit:"continental airlines",PrimLangInfo:"",SecLang_word:"కాంటినెంటల్ ఎయిర్ లైన్స్",SecLang_sound_url:"",SecLang_translit:"కాంటినెంటల్ ఎయిర్ లైన్స్",Image:"http://www.underconsideration.com/brandnew/archives/united_continental_logo.gif"},
{PrimLang_word:"delta",PrimLang_sound_url:"",PrimLang_translit:"delta",PrimLangInfo:"",SecLang_word:"డెల్టా",SecLang_sound_url:"",SecLang_translit:"డెల్టా",Image:"http://images.wikia.com/logopedia/images/5/5a/Delta_Air_Lines.svg"},
{PrimLang_word:"frontier airlines",PrimLang_sound_url:"",PrimLang_translit:"frontier airlines",PrimLangInfo:"",SecLang_word:"ఫ్రా౦టియర్ ఎయిర్ లైన్స్",SecLang_sound_url:"",SecLang_translit:"ఫ్రా౦టియర్ ఎయిర్ లైన్స్",Image:"http://upload.wikimedia.org/wikipedia/commons/c/cc/Frontier_Airlines_Logo.svg"},
{PrimLang_word:"iceland air",PrimLang_sound_url:"",PrimLang_translit:"iceland air",PrimLangInfo:"",SecLang_word:"ఐస్ ల్యాండ్ ఎయిర్",SecLang_sound_url:"",SecLang_translit:"ఐస్ ల్యాండ్ ఎయిర్",Image:"http://upload.wikimedia.org/wikipedia/en/thumb/d/d4/Icelandair_logo.svg/500px-Icelandair_logo.svg.png"},
{PrimLang_word:"southwest",PrimLang_sound_url:"",PrimLang_translit:"southwest",PrimLangInfo:"",SecLang_word:"సౌత్ వెస్ట్.కామ్",SecLang_sound_url:"",SecLang_translit:"సౌత్ వెస్ట్.కామ్",Image:"http://upload.wikimedia.org/wikipedia/en/2/2e/Southwest_Airlines_Logo.png"},
{PrimLang_word:"sun country airlines",PrimLang_sound_url:"",PrimLang_translit:"sun country airlines",PrimLangInfo:"",SecLang_word:"సన్ కంట్రీ ఎయిర్ లైన్స్",SecLang_sound_url:"",SecLang_translit:"సన్ కంట్రీ ఎయిర్ లైన్స్",Image:"http://www3.airlinesanddestinations.com/wp-content/uploads/2010/12/101207-SunCountry-01.jpg"},
{PrimLang_word:"united",PrimLang_sound_url:"",PrimLang_translit:"united",PrimLangInfo:"",SecLang_word:"యునై టెడ్",SecLang_sound_url:"",SecLang_translit:"యునై టెడ్",Image:"http://upload.wikimedia.org/wikipedia/en/e/e0/United_Airlines_Logo.svg"},
{PrimLang_word:"US airways",PrimLang_sound_url:"",PrimLang_translit:"US airways",PrimLangInfo:"",SecLang_word:"యు ఎస్ ఎయిర్ వేస్",SecLang_sound_url:"",SecLang_translit:"యు ఎస్ ఎయిర్ వేస్",Image:"http://nothingcannothappen.files.wordpress.com/2010/12/us-air-logo.jpg"}
]