var EnglishTelugu_Chinese_Zodiac_Signs=
	[
	 {PrimLang_word:"Pig",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"",Image:"http://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Boar.svg/500px-Boar.svg.png"},
	 {PrimLang_word:"Dog",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"",Image:"http://upload.wikimedia.org/wikipedia/commons/e/ef/DogYearPaperCutting.jpg"},
	 {PrimLang_word:"Rooster",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"",Image:"http://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Rooster.svg/500px-Rooster.svg.png"},
	 {PrimLang_word:"Monkey",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"",Image:"http://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Monkey.svg/200px-Monkey.svg.png"},
	 {PrimLang_word:"Sheep",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"",Image:"http://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Goat.svg/500px-Goat.svg.png"},
	 {PrimLang_word:"Horse",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"",Image:"http://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Horse.svg/500px-Horse.svg.png"},
	 {PrimLang_word:"Snake",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"",Image:"http://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Snake.svg/500px-Snake.svg.png"},
	 {PrimLang_word:"Dragon",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"",Image:"http://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Dragon.svg/500px-Dragon.svg.png"},
	 {PrimLang_word:"Rabbit",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"",Image:"http://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Rabbit.svg/500px-Rabbit.svg.png"},
	 {PrimLang_word:"Tiger",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"",Image:"http://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Tiger.svg/500px-Tiger.svg.png"},
	 {PrimLang_word:"Ox",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"",Image:"http://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Oxen.svg/500px-Oxen.svg.png"},
	 {PrimLang_word:"Rat",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"",Image:"http://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Rat.svg/500px-Rat.svg.png"}
	 ]