var EnglishTelugu_toys=
	[
	 {PrimLang_word:"",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"క్లాసిక్ యో యో",Image:"http://m4.i.pbase.com/u9/willa/medium/4113844.ClassicYoYoBlue.jpg"},
	 {PrimLang_word:"",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"బంగాళాదుంప స్థితి",Image:"http://f00.inventorspot.com/images/6_1202toys.jpg"},
	 {PrimLang_word:"",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"Rubics క్యూబ్",Image:"http://www.millionaireplayboy.com/mpb/wp-content/uploads/2009/06/rubiks-cube.jpg"},
	 {PrimLang_word:"",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"బ్రిక్స్",Image:"http://alt.coxnewsweb.com/cnishared/tools/shared/mediahub/09/76/37/slideshow_1377697_toys.0315sbe_01.JPG"},
	 {PrimLang_word:"",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"టాయ్ బాక్స్",Image:"http://toybox101.com/wp-content/uploads/2010/05/classic_toys-playdoh.jpg"},
	 {PrimLang_word:"",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"లిటిల్ రెడ్ వాగన్",Image:"http://4.bp.blogspot.com/_vvAhyR-6PAM/SwNT_KhycbI/AAAAAAAADOQ/IAxwKNSPDhU/s1600/146806-main_Full.jpg"},
	 {PrimLang_word:"",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"ETCH-A-స్కెచ్",Image:"http://2.bp.blogspot.com/_vvAhyR-6PAM/SwNUNLEQPBI/AAAAAAAADOo/8OWla3SDK34/s1600/flair-classic-etch-a-sketch-the-worlds-favourite-drawing-toy.jpg"},
	 {PrimLang_word:"",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"లింకన్ చిట్టాలు",Image:"http://2.bp.blogspot.com/_vvAhyR-6PAM/SwNUbNBQUQI/AAAAAAAADPI/iH1X0lW_oOk/s1600/lincolnlogs.jpg"},
	 {PrimLang_word:"",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"చూడండి మాస్టర్",Image:"http://4.bp.blogspot.com/_vvAhyR-6PAM/SwNUxJCmA-I/AAAAAAAADQI/T4hfBzJUm78/s1600/viewmasterviewer.jpg"},
	 {PrimLang_word:"",PrimLang_sound_url:"",PrimLang_translit:"",PrimLangInfo:"",SecLang_word:"",SecLang_sound_url:"",SecLang_translit:"slinky",Image:"http://3.bp.blogspot.com/_vvAhyR-6PAM/SwNUwj3r3aI/AAAAAAAADP4/sCQedq8Wd0E/s320/slinky-popular-culture-classic-toy.jpg"}
	 ]