[
  {
    "English":"grandmother",
    "Lang":"అమ్మమ్మ",
    "EnglisSounds":"GRANDMOTHER",
    "LangSounds":"MAMA",
    "Category":"family",
    "Langinlang":"కుటుంబం",
    "Image":"http://evolutionofhatred.files.wordpress.com/2011/11/grandmother-festival1.jpg",
    "Info":"http://en.wikipedia.org/wiki/Grandmother",
    "EnglishSound":"https://ssl.gstatic.com/dictionary/static/sounds/de/0/grandmother.mp3"
  },
  {
    "English":"grandfather",
    "Lang":"తాత",
    "EnglisSounds":"GRANDFATHER",
    "LangSounds":"TATA",
    "Category":"family",
    "Langinlang":"కుటుంబం",
    "Image":"http://upload.wikimedia.org/wikipedia/commons/4/46/My_Grandfather_Photo_from_January_17.JPG",
    "Info":"http://en.wikipedia.org/wiki/Grandfather",
    "EnglishSound":"https://ssl.gstatic.com/dictionary/static/sounds/de/0/grandfather.mp3"
  },
  {
    "English":"mother",
    "Lang":"తల్లి",
    "EnglisSounds":"MOTHER",
    "LangSounds":"MADRAY",
    "Category":"family",
    "Langinlang":"కుటుంబం",
    "Image":"http://niniu.ir/wp-content/uploads/2012/07/photograph-mother-baby.jpg",
    "Info":"http://en.wikipedia.org/wiki/Mother",
    "EnglishSound":"https://ssl.gstatic.com/dictionary/static/sounds/de/0/mother.mp3"
  },
  {
    "English":"father",
    "Lang":"తండ్రి",
    "EnglisSounds":"FATHER",
    "LangSounds":"TANDRI",
    "Category":"family",
    "Langinlang":"కుటుంబం",
    "Image":"http://healthynaturalbaby.org/wp-content/uploads/2013/06/father_bonding_with_baby.jpg",
    "Info":"http://en.wikipedia.org/wiki/Father",
    "EnglishSound":"https://ssl.gstatic.com/dictionary/static/sounds/de/0/father.mp3"
  },
  {
    "English":"uncle",
    "Lang":"మామయ్య",
    "EnglisSounds":"UNCLE",
    "LangSounds":"TEE-O",
    "Category":"family",
    "Langinlang":"కుటుంబం",
    "Image":"http://juliaarabia.com/wp-content/uploads/2013/07/tumblr_m57p07I0Nd1qb4l5ro1_500.jpg",
    "Info":"http://en.wikipedia.org/wiki/Uncle",
    "EnglishSound":"https://ssl.gstatic.com/dictionary/static/sounds/de/0/uncle.mp3"
  },
  {
    "English":"aunt",
    "Lang":"అత్త",
    "EnglisSounds":"AUNT",
    "LangSounds":"TEE-AH",
    "Category":"family",
    "Langinlang":"కుటుంబం",
    "Image":"http://upload.wikimedia.org/wikipedia/en/f/fb/First_Episode_Aunt_Bee_10101.JPG",
    "Info":"http://en.wikipedia.org/wiki/Aunt",
    "EnglishSound":"https://ssl.gstatic.com/dictionary/static/sounds/de/0/aunt.mp3"
  },
  {
    "English":"cousin",
    "Lang":"దాయాది",
    "EnglisSounds":"COUSIN",
    "LangSounds":"PREE-MO",
    "Category":"family",
    "Langinlang":"కుటుంబం",
    "Image":"http://4.bp.blogspot.com/_Jis4gwoR0R8/TIPdNTjl65I/AAAAAAAAAI4/VvmqZdehjGE/s400/33104-Clipart-Illustration-Of-Two-Little-Boys-Laughing-And-Talking-At-A-Bus-Stop.jpg",
    "Info":"http://en.wikipedia.org/wiki/Cousin",
    "EnglishSound":"https://ssl.gstatic.com/dictionary/static/sounds/de/0/cousin.mp3"
  },
  {
    "English":"brother ",
    "Lang":"సోదరుడు",
    "EnglisSounds":"BROTHER",
    "LangSounds":"AIR-MAH-NO",
    "Category":"family",
    "Langinlang":"కుటుంబం",
    "Image":"http://www.maiseymae.com/images/detailed/0/BigBrother_Boy.jpg",
    "Info":"http://en.wikipedia.org/wiki/Brother",
    "EnglishSound":"https://ssl.gstatic.com/dictionary/static/sounds/de/0/brother.mp3"
  },
  {
    "English":"sister",
    "Lang":"సోదరి",
    "EnglisSounds":"SISTER",
    "LangSounds":"AIR-MAH-NAH",
    "Category":"family",
    "Langinlang":"కుటుంబం",
    "Image":"http://content.mycutegraphics.com/graphics/fam/sisters.png",
    "Info":"http://en.wikipedia.org/wiki/Sister",
    "EnglishSound":"https://ssl.gstatic.com/dictionary/static/sounds/de/0/sister.mp3"
  },
  {
    "English":"son",
    "Lang":"కుమారుడు ",
    "EnglisSounds":"SON",
    "LangSounds":"EHO",
    "Category":"family",
    "Langinlang":"కుటుంబం",
    "Image":"http://i2.cdn.turner.com/cnn/dam/assets/120424041148-golf-els-son-story-top.jpg",
    "Info":"http://en.wikipedia.org/wiki/Son",
    "EnglishSound":"https://ssl.gstatic.com/dictionary/static/sounds/de/0/son.mp3"
  },
  {
    "English":"daughter",
    "Lang":"కుమార్తె",
    "EnglisSounds":"DAUGHTER",
    "LangSounds":"EHA",
    "Category":"family",
    "Langinlang":"కుటుంబం",
    "Image":"http://z.about.com/d/womensissues/1/0/0/4/-/-/ObamaDaughterCrop.jpg",
    "Info":"http://en.wikipedia.org/wiki/Daughter",
    "EnglishSound":"https://ssl.gstatic.com/dictionary/static/sounds/de/0/daughter.mp3"
  },
  {
    "English":"grandson",
    "Lang":"గ్రాండ్సన్ ",
    "EnglisSounds":"GRANDSON",
    "LangSounds":"NE-ATO",
    "Category":"family",
    "Langinlang":"కుటుంబం",
    "Image":"http://orrinwoodwardblog.com/wp-content/uploads/2011/08/grandfather_with_grandson.jpg",
    "Info":"http://en.wikipedia.org/wiki/Family",
    "EnglishSound":"https://ssl.gstatic.com/dictionary/static/sounds/de/0/grandson.mp3"
  },
  {
    "English":"granddaughter",
    "Lang":"మనుమరాలు",
    "EnglisSounds":"GRANDDAUGHTER",
    "LangSounds":"NE-ATAH",
    "Category":"family",
    "Langinlang":"కుటుంబం",
    "Image":"http://thumbs.dreamstime.com/z/grandma-granddaughter-13957164.jpg",
    "Info":"http://en.wikipedia.org/wiki/Family",
    "EnglishSound":"https://ssl.gstatic.com/dictionary/static/sounds/de/0/granddaughter.mp3"
  }
];